SELECT * FROM customer limit 20

--Q1. what is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) as revenue from customer
group by gender

--Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount from customer_behavior
where discount_applied='Yes' and (select Avg(purc))

--Q3. Which are the top 5 products with the highest average review rating?

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers. 06. which 5 products have the highest percentage of purchases with discounts applied?

--Q7. Segment customers Into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.

--QB. What are the top 3 most purchased products within each category?

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe

--Q10. what is the revenue contribution of each age group? 
